[workspace]
resolver = "3"
members = ["crates/*", "learn/*", "learn/01_base/connection", "learn/01_base/server"]
exclude = ["learn/01_base"]

[workspace.package]
authors = ["Dima P <dimapm@pm.me>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/di-rs/async_rust"
readme = "README.md"
include = ["README.md", "LICENSE", "build.rs", "Cargo.toml", "src/**/*.rs"]

[workspace.dependencies]

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
