[package]
name = "sandbox"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
include.workspace = true

[dependencies]
reqwest = "0.13.5"
tokio = { version ="1.53.1", features = ["full"] }

[lints]
workspace = true
